// Country list with timezone mappings
export const COUNTRIES = [
  { code: 'US', name: 'United States', timezone: 'America/New_York' },
  { code: 'CA', name: 'Canada', timezone: 'America/Toronto' },
  { code: 'GB', name: 'United Kingdom', timezone: 'Europe/London' },
  { code: 'IE', name: 'Ireland', timezone: 'Europe/Dublin' },
  { code: 'AU', name: 'Australia', timezone: 'Australia/Sydney' },
  { code: 'NZ', name: 'New Zealand', timezone: 'Pacific/Auckland' },
  { code: 'DE', name: 'Germany', timezone: 'Europe/Berlin' },
  { code: 'FR', name: 'France', timezone: 'Europe/Paris' },
  { code: 'ES', name: 'Spain', timezone: 'Europe/Madrid' },
  { code: 'IT', name: 'Italy', timezone: 'Europe/Rome' },
  { code: 'NL', name: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { code: 'BE', name: 'Belgium', timezone: 'Europe/Brussels' },
  { code: 'CH', name: 'Switzerland', timezone: 'Europe/Zurich' },
  { code: 'AT', name: 'Austria', timezone: 'Europe/Vienna' },
  { code: 'SE', name: 'Sweden', timezone: 'Europe/Stockholm' },
  { code: 'NO', name: 'Norway', timezone: 'Europe/Oslo' },
  { code: 'DK', name: 'Denmark', timezone: 'Europe/Copenhagen' },
  { code: 'FI', name: 'Finland', timezone: 'Europe/Helsinki' },
  { code: 'PL', name: 'Poland', timezone: 'Europe/Warsaw' },
  { code: 'PT', name: 'Portugal', timezone: 'Europe/Lisbon' },
  { code: 'GR', name: 'Greece', timezone: 'Europe/Athens' },
  { code: 'IN', name: 'India', timezone: 'Asia/Kolkata' },
  { code: 'CN', name: 'China', timezone: 'Asia/Shanghai' },
  { code: 'JP', name: 'Japan', timezone: 'Asia/Tokyo' },
  { code: 'KR', name: 'South Korea', timezone: 'Asia/Seoul' },
  { code: 'SG', name: 'Singapore', timezone: 'Asia/Singapore' },
  { code: 'HK', name: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
  { code: 'MY', name: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
  { code: 'TH', name: 'Thailand', timezone: 'Asia/Bangkok' },
  { code: 'PH', name: 'Philippines', timezone: 'Asia/Manila' },
  { code: 'ID', name: 'Indonesia', timezone: 'Asia/Jakarta' },
  { code: 'VN', name: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'AE', name: 'United Arab Emirates', timezone: 'Asia/Dubai' },
  { code: 'SA', name: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { code: 'IL', name: 'Israel', timezone: 'Asia/Jerusalem' },
  { code: 'BR', name: 'Brazil', timezone: 'America/Sao_Paulo' },
  { code: 'MX', name: 'Mexico', timezone: 'America/Mexico_City' },
  { code: 'AR', name: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
  { code: 'CL', name: 'Chile', timezone: 'America/Santiago' },
  { code: 'CO', name: 'Colombia', timezone: 'America/Bogota' },
  { code: 'ZA', name: 'South Africa', timezone: 'Africa/Johannesburg' },
  { code: 'NG', name: 'Nigeria', timezone: 'Africa/Lagos' },
  { code: 'KE', name: 'Kenya', timezone: 'Africa/Nairobi' },
  { code: 'EG', name: 'Egypt', timezone: 'Africa/Cairo' },
  { code: 'RU', name: 'Russia', timezone: 'Europe/Moscow' },
  { code: 'TR', name: 'Turkey', timezone: 'Europe/Istanbul' },
  { code: 'PK', name: 'Pakistan', timezone: 'Asia/Karachi' },
  { code: 'BD', name: 'Bangladesh', timezone: 'Asia/Dhaka' },
] as const

export const TIMEZONES = [
  { value: 'UTC', label: 'UTC (GMT+0)', offset: 0 },
  { value: 'America/New_York', label: 'Eastern Time (ET) - New York', offset: -5 },
  { value: 'America/Chicago', label: 'Central Time (CT) - Chicago', offset: -6 },
  { value: 'America/Denver', label: 'Mountain Time (MT) - Denver', offset: -7 },
  { value: 'America/Los_Angeles', label: 'Pacific Time (PT) - Los Angeles', offset: -8 },
  { value: 'America/Toronto', label: 'Eastern Time - Toronto', offset: -5 },
  { value: 'America/Vancouver', label: 'Pacific Time - Vancouver', offset: -8 },
  { value: 'Europe/London', label: 'London (GMT)', offset: 0 },
  { value: 'Europe/Paris', label: 'Paris (CET)', offset: 1 },
  { value: 'Europe/Berlin', label: 'Berlin (CET)', offset: 1 },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (CET)', offset: 1 },
  { value: 'Europe/Madrid', label: 'Madrid (CET)', offset: 1 },
  { value: 'Europe/Rome', label: 'Rome (CET)', offset: 1 },
  { value: 'Europe/Dublin', label: 'Dublin (GMT)', offset: 0 },
  { value: 'Europe/Stockholm', label: 'Stockholm (CET)', offset: 1 },
  { value: 'Europe/Moscow', label: 'Moscow (MSK)', offset: 3 },
  { value: 'Asia/Dubai', label: 'Dubai (GST)', offset: 4 },
  { value: 'Asia/Kolkata', label: 'India (IST)', offset: 5.5 },
  { value: 'Asia/Shanghai', label: 'Shanghai/Beijing (CST)', offset: 8 },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)', offset: 9 },
  { value: 'Asia/Seoul', label: 'Seoul (KST)', offset: 9 },
  { value: 'Asia/Singapore', label: 'Singapore (SGT)', offset: 8 },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (HKT)', offset: 8 },
  { value: 'Australia/Sydney', label: 'Sydney (AEDT)', offset: 11 },
  { value: 'Australia/Melbourne', label: 'Melbourne (AEDT)', offset: 11 },
  { value: 'Pacific/Auckland', label: 'Auckland (NZDT)', offset: 13 },
  { value: 'America/Sao_Paulo', label: 'São Paulo (BRT)', offset: -3 },
  { value: 'America/Mexico_City', label: 'Mexico City (CST)', offset: -6 },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (SAST)', offset: 2 },
  { value: 'Africa/Lagos', label: 'Lagos (WAT)', offset: 1 },
  { value: 'Africa/Cairo', label: 'Cairo (EET)', offset: 2 },
] as const

export function getTimezoneForCountry(countryCode: string): string {
  const country = COUNTRIES.find(c => c.code === countryCode)
  return country?.timezone || 'UTC'
}

export function getCountryName(countryCode: string): string {
  const country = COUNTRIES.find(c => c.code === countryCode)
  return country?.name || countryCode
}
